# -*- coding: utf-8 -*-
"""ICP4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OtfWjxijc3wZ78X2k1x-bj3_2zrxAUL0
"""

from werkzeug.utils import secure_filename
import joblib
from flask import Flask, request, render_template
import cv2
import numpy as np

# Define a flask app
app = Flask(_name_)

def process_eval(imk):
    output1 = cv2.resize(imk, (50,50))
    output1 = output1.astype('float')
    output1 /= 255.0
    print(type(output1))
    output1 = np.array(output1).reshape(-1, 50, 50, 3)
    classifer = joblib.load("sreevalli.pk2")
    x = classifer.predict_classes(output1[[0], :])
    if x[0] == 1:
        result = "PREDICTED RESULT IS FLIGHT"
    else:
        result = "PREDICTED RESULT IS CAR"
    return result

@app.route('/', methods=['GET'])
def index():
   return render_template('index.html')

@app.route('/', methods=['GET', 'POST'])
def handle_form():
    if request.method == 'POST':
        file = request.files['file']
        file.save(secure_filename("save.jpeg"))
        im=cv2.imread("save.jpeg")
        result=process_eval(im)
        return render_template('index.html',result=result)

if _name_ == "_main_":
    app.run()